# Getting Started with DaCe

DaCe is a Python library that enables optimizing code with ease, from running on a single core to a full supercomputer. With the power of data-centric transformations, it can automatically map code for CPUs, GPUs, and FPGAs.

Let's get started with DaCe by importing it:

In [16]:
import dace

A data-centric program can be generated from several general-purpose and domain-specific languages. Our main frontend, however, is Python/numpy. To define a program, we take an existing function on numpy arrays and decorate it with `@dace.program`:

In [17]:
@dace.program
def getstarted(A):
    return A + A

Running our dace program, we will see several outputs and a prompt. These are the available transformations we can apply. For the first step, we opt to apply none (press Enter) and proceed with compilation and running:

In [3]:
import numpy as np
a = np.random.rand(2, 3)
a

array([[0.02638476, 0.15801766, 0.60640768],
       [0.75281897, 0.02027034, 0.92066681]])

In [4]:
getstarted(a)

array([[0.05276951, 0.31603533, 1.21281536],
       [1.50563794, 0.04054068, 1.84133362]])

The results are, as expected, `2*A`.

Now, let's inspect the intermediate representation of the data-centric program, its Stateful Dataflow Multigraph (SDFG):

In [18]:
getstarted.to_sdfg(a)

SDFG (getstarted)

You can drag the handle at the bottom right to make the SDFG frame larger.

Notice the following four elements in the graph:

1. **State** (blue region): This is the control flow part of the application, represented as a state machine. Since there is no control-flow in the data-centric representation of `A+A`, we see only one state encompassing the computation.
2. **Arrays** (circular nodes) and **Memlets** (arrows): These nodes represent disjoint N-dimensional memory regions (similar to numpy `ndarray`s), and the edges represent data that is moved throughout the state. Hovering over a memlet will show more information about the subset being moved.
3. **Tasklets** (octagon): This node represents the computational parts of the graph. Zooming into it will show the code (addition operation in this case). Tasklets act as pure functions that can only work with the data coming into/out of its **connectors** (cyan circles on the node).
4. **Maps** (trapezoid): Anything that is enclosed between these two nodes (the map *scope*) is replicated for the number of times specified on the node (in our case, `2*3` times). This creates parametric parallelism in the graph and can be nested in each other for efficient parallelization and distribution of work.

Unfortunately (or fortunately in some cases), this graph is specialized for a specific size of array (as given to it), and will not work on other sizes. To compile a program that works with general sizes, we'll need to use symbolic sizes.

## Symbols

DaCe includes a symbolic math engine (extending SymPy) to support symbolic expressions for sizes, ranges, accesses, and more. 

Any number of symbols can be used throughout a computation. Defining a symbol is as easy as calling:

In [19]:
N = dace.symbol('N')

which we can now use for any computation and definitions. For example, annotating the types of our function from above will yield a version that works with any size:

In [20]:
@dace.program
def getstarted_sym(A: dace.float64[N, 2*N]):
    return A + A

In [21]:
getstarted_sym.to_sdfg()

SDFG (getstarted_sym)

If we compile this code, any array that can match a size of `Nx2N` will be automatically used to infer the value of `N` and invoke the function:

In [9]:
getstarted_sym(np.random.rand(100, 200))

array([[0.98818461, 1.27933885, 0.2033508 , ..., 0.547033  , 0.4299565 ,
        0.24654365],
       [1.91945996, 0.8587834 , 1.6074685 , ..., 0.60969216, 1.7881462 ,
        1.6251679 ],
       [0.09656663, 0.86573612, 0.79912191, ..., 1.50199177, 0.14342504,
        0.77152323],
       ...,
       [1.86926975, 0.16524055, 0.57659078, ..., 0.06706506, 1.94858343,
        0.21332081],
       [0.78987173, 0.32493361, 0.33111051, ..., 0.41438505, 1.6625166 ,
        1.4539469 ],
       [0.32619914, 0.84155838, 0.85757214, ..., 0.93809   , 0.25236549,
        1.95588663]])

## Performance

Given our symbolic SDFG, we would not like to recompile it every time. Thus, we can pre-compile the graph into an .so/.dll file:

In [10]:
csdfg = getstarted_sym.compile()

A compiled SDFG, however, has to be invoked like an SDFG, with keyword arguments only:

In [11]:
b = csdfg(A=np.random.rand(10,20), N=np.int32(10))

We can now see the performance of the code on large arrays vs. numpy:

In [12]:
tester = np.random.rand(2000, 4000)

In [13]:
%timeit tester + tester

12 ms ± 258 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
%timeit csdfg(A=tester, N=np.int32(2000))

5.1 ms ± 470 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Explicit Dataflow

One can specify explicit dataflow in dace using `for i in dace.map[begin:end]:` syntax, as well as tasklets manually using `with dace.tasklet:`. Here is an example of a real-world example (Scattering Self-Energies) with an 8-dimensional parallel computation:

In [22]:
# Declaration of symbolic variables
Nkz, NE, Nqz, Nw, N3D, NA, NB, Norb = (
    dace.symbol(name)
    for name in ['Nkz', 'NE', 'Nqz', 'Nw', 'N3D', 'NA', 'NB', 'Norb'])


@dace.program
def sse_sigma(neigh_idx: dace.int32[NA, NB],
              dH: dace.complex128[NA, NB, N3D, Norb, Norb],
              G: dace.complex128[Nkz, NE, NA, Norb, Norb],
              D: dace.complex128[Nqz, Nw, NA, NB, N3D, N3D],
              Sigma: dace.complex128[Nkz, NE, NA, Norb, Norb]):

    # Declaration of Map scope
    for k, E, q, w, i, j, a, b in dace.map[0:Nkz, 0:NE, 0:Nqz, 0:Nw, 0:N3D, 0:
                                           N3D, 0:NA, 0:NB]:
        dHG = G[k - q, E - w, neigh_idx[a, b]] @ dH[a, b, i]
        dHD = dH[a, b, j] * D[q, w, a, b, i, j]
        Sigma[k, E, a] += dHG @ dHD
        
sse_sigma.to_sdfg()

SDFG (sse_sigma)